### ISSUE TITLE
Adding unreal.hx to engine from source with Nvidia Gameworks

### ISSUE THREAD

**Issue by datee** [proletariatgames/unreal.hx#114]
So im trying to build a 4.19 version of the engine thats merged with gameworks but im getting some errors... So im wondering ...Is this possible to do at all?

`C:/projects/TekniskMuseum/Vannkraft/utvikling/Vannkraftverk/Intermediate/Haxe/Vannkraftverk-Win-Development-Editor/Generated/Private/uhx/glues/ECollisionChannel_Glue.cpp(65): error C2065: 'ECC_EngineTraceChannel6': undeclared identifier
2>C:/projects/TekniskMuseum/Vannkraft/utvikling/Vannkraftverk/Intermediate/Haxe/Vannkraftverk-Win-Development-Editor/Generated/Private/uhx/glues/ECollisionChannel_Glue.cpp(65): error C2131: expression did not evaluate to a constant
2>  C:/projects/TekniskMuseum/Vannkraft/utvikling/Vannkraftverk/Intermediate/Haxe/Vannkraftverk-Win-Development-Editor/Generated/Private/uhx/glues/ECollisionChannel_Glue.cpp(65): note: failure was caused by non-constant arguments or reference to a non-constant symbol
2>  C:/projects/TekniskMuseum/Vannkraft/utvikling/Vannkraftverk/Intermediate/Haxe/Vannkraftverk-Win-Development-Editor/Generated/Private/uhx/glues/ECollisionChannel_Glue.cpp(65): note: see usage of 'ECC_EngineTraceChannel6'
2>C:/projects/TekniskMuseum/Vannkraft/utvikling/Vannkraftverk/Intermediate/Haxe/Vannkraftverk-Win-Development-Editor/Generated/Private/uhx/glues/ECollisionChannel_Glue.cpp(65): error C2051: case expression not constant
2>C:/projects/TekniskMuseum/Vannkraft/utvikling/Vannkraftverk/Intermediate/Haxe/Vannkraftverk-Win-Development-Editor/Generated/Private/uhx/glues/ECollisionChannel_Glue.cpp(139): error C2065: 'ECC_EngineTraceChannel6': undeclared identifier
2>C:/projects/TekniskMuseum/Vannkraft/utvikling/Vannkraftverk/Intermediate/Haxe/Vannkraftverk-Win-Development-Editor/Generated/Private/uhx/glues/FCollisionResponseContainer_Glue.cpp(137): error C2039: 'EngineTraceChannel6': is not a member of 'FCollisionResponseContainer'
2>  D:\work\unreal\UE419-GW\Engine\Source\Runtime\Engine\Classes\Engine/EngineTypes.h(872): note: see declaration of 'FCollisionResponseContainer'
2>C:/projects/TekniskMuseum/Vannkraft/utvikling/Vannkraftverk/Intermediate/Haxe/Vannkraftverk-Win-Development-Editor/Generated/Private/uhx/glues/FCollisionResponseContainer_Glue.cpp(140): error C2039: 'EngineTraceChannel6': is not a member of 'FCollisionResponseContainer'
2>  D:\work\unreal\UE419-GW\Engine\Source\Runtime\Engine\Classes\Engine/EngineTypes.h(872): note: see declaration of 'FCollisionResponseContainer'`

This fork:
https://github.com/0lento/UnrealEngine/tree/4.19-GameWorks

**Comment by waneck** [comment]
Hey! Sorry I missed this issue and didn't get back to you sooner
So, it IS possible but you may need to re-generate your own externs. In order to do that, you will first need to compile the UnrealHxGenerator plugin ( https://github.com/proletariatgames/UnrealHxGenerator ) following the instructions in the README file, then do the following:

* create an empty project
* build it once
* I think by then you might be able to just run the build with the environment variables GENERATE_EXTERNS=1 , and EXTERN_OUTPUT_DIR=/some/temp/path

If not:
* edit the .uproject to explicitly reference the UnrealHxGenerator plugin (and make it enabled)
* find the generated .uhtmanifest (in Intermediates)
* call UnrealHeaderTool with the above environment variables, and the following arguments:
    UnrealHeaderTool /path/to/uproject.uproject /path/to/uhtmanifest.uhtmanifest -PLUGIN=UnrealHxGenerator

**Comment by datee** [comment]
Hi!!
Thanks so much for this! With your help I was able to get it working! 👍 :)
Had some errors while generating the externs, dont know how important that is?

[log.txt](https://github.com/proletariatgames/unreal.hx/files/2379394/log.txt)
[errors.txt](https://github.com/proletariatgames/unreal.hx/files/2379395/errors.txt)

**Comment by waneck** [comment]
That's awesome! The errors aren't important at all - they always happen and are only warnings about some property types we still don't automatically generate externs for.

Have you been able to get everything working?

**Comment by datee** [comment]
Looks good so far. Took a bit fail and try getting the build and my own externs right. But i was able to get unreal.hx working with the full Gameworks fork (VXGI, Flex, Blast, etc), and my game haxe framework written for the 4.19 launcher version. :)

**Comment by waneck** [comment]
That's great! Let me know if you need any support in unreal.hx itself - I haven't thought about adding a setting for custom engine externs, but that shouldn't be hard to add

**Comment by waneck** [comment]
I'm going to close this - but feel free to reopen/open new issues if you find other issues
