### ISSUE TITLE
4.20 support

### ISSUE THREAD

**Issue by iainmckay** [proletariatgames/unreal.hx#116]
What would it take to support 4.20?

**Comment by mfoda** [comment]
Curious about this too. I noticed there's #118 but I'm not sure what that means for UE 4.2+ support since it hasn't been merged into `development` yet.

I'm pretty new to Haxe and looking for a good challenge, so if someone could outline the necessary steps to make this work I would love to help make it happen :-)

**Comment by mfoda** [comment]
Alternatively, if this is a big task and requires a lot of time, would it be possible in the meantime to use UnrealHx in a UE 4.19 project and copy over the generated C++ files to use in UE 4.2+, assuming that the code is strictly 4.19 api compatible? Hope this is not a stupid question.

**Comment by datee** [comment]
Current development branch is compatible with 4.21

**Comment by mfoda** [comment]
Good to know @datee. Thanks for the heads up!

**Comment by silvioterra** [comment]
With latest development ([CL-32265] commit 4b1879c) and 4.21.2 From the Epic Games Launcher (vanilla download, not github download), it seems that the haxe build step is failing. Attached is the output from a test with an Unreal project made via the launcher, C++ 'blank' template and with only the 'HaxeModuleRules' change.

Tested with haxe 3.4.7 as well as haxe 4.0.0-rc2

[unreal.hx_4.21.2_haxe_3.4.7.txt](https://github.com/proletariatgames/unreal.hx/files/3025268/unreal.hx_4.21.2_haxe_3.4.7.txt)
[unreal.hx_4.21.2_haxe_4rc2.txt](https://github.com/proletariatgames/unreal.hx/files/3025269/unreal.hx_4.21.2_haxe_4rc2.txt)

Are there any steps that are different from the ones described in readme.md? 

Thanks.
