### ISSUE TITLE
4.22.3 FText::AsHourMinuteTimespan

### ISSUE THREAD

**Issue by thejustinwalsh** [proletariatgames/unreal.hx#134]
Using UE 4.22.3 `FText::AsHourMinuteTimespan` does not exist and causes a compilation error.
https://github.com/proletariatgames/unreal.hx/blob/bd9cd5bf888f1e521f53fca7b752c224263f98bc/Haxe/Externs/Common/unreal/FTextImpl.hx#L13

**Comment by datee** [comment]
Its a known bug, i guess. Easy fix though.
https://github.com/proletariatgames/unreal.hx/issues/126#issuecomment-506637169

**Comment by thejustinwalsh** [comment]
Missed that thread. Thank you.
