### ISSUE TITLE
Recommended Unreal/Haxe Versions

### ISSUE THREAD

**Issue by peteshand** [proletariatgames/unreal.hx#139]
Hi there

What are the current recommended versions for Unreal and Haxe?

I've been trying to get a barebones project up and running, (using MacOS). I've tried multiple versions of Unreal, however keep running into compilation errors at the baking externs stage.

If anyone has a working setup (ideally on mac) i'd love to know the config.

**Comment by peteshand** [comment]
Guys this is a simple question... anyone?

Is this project active?

**Comment by datee** [comment]
Last compatible versions as far as i know is UE4 4.22 / Haxe 4

**Comment by peteshand** [comment]
✌️ thanks
