### ISSUE TITLE
More Examples

### ISSUE THREAD

**Issue by andrewmunro** [proletariatgames/unreal.hx#35]
This looks promising, but could you please provide more examples. I'm finding that the `AMyActor` example isn't working, I've tried putting a simple trace in the `Tick` function, but it doesn't seem to be called.

This is possibly because `PrimaryActorTick.bCanEverTick` is never set to true, but I can't figure out how you actually create a constructor to set it...

Could you maybe post a few more examples to get an idea of the basic workflow.

**Comment by andrewmunro** [comment]
I finally got it working. I think I messed up somehow and my changes weren't being compiled with ccpia.

Here's my code for anyone else stuck:

```
package playground;

import unreal.*;

@:uclass
class AMyActor extends AActor
{
    // make a property that is editable in the editor.
    @:uproperty(EditDefaultsOnly, Category=Inventory)
    var items:TArray<AActor>;

    public function new(wrapped:cpp.Pointer<Dynamic>)
    {
        super(wrapped);
        PrimaryActorTick.bCanEverTick = true;
    }

    // make a function that is callable from C++/Blueprints
    @:ufunction(BlueprintCallable, Category=Inventory)
    public function addToInventory(item:AActor)
    {
        items.push(item);
    }

    // override native C++ function
    override function Tick(deltaTime:Float32) : Void
    {
        super.Tick(deltaTime);
        trace("Hello world!");
    }
}

```
I still stand that an example project would be good, as well as an outline on best practices. I am a little confused as to the development process. Do you tend to create classes in the /Scripts folder, and when you are happy move it across to /Static ?

**Comment by waneck** [comment]
Thank you for the fixes. I've updated the README, and also added a link to https://github.com/waneck/HaxePlatformerGame , which is the latest full example of using Haxe.

The best way is to always use Scripts, and just move to Static when you realize that the game is running slow, or that it works better when compiled with hxcpp directly.

Feel free to reopen the issue if you run into any problem.
Thanks
