### ISSUE TITLE
How to 'port build.cs to build.hx'

### ISSUE THREAD

**Issue by parasetamon** [proletariatgames/unreal.hx#38]
I don't know all haxe syntax but I'm very interesting to this project, but please give me an example of porting .build. Cause I'm stuck at that process. Can we use tool ? If not, how ?

Thank you.

**Comment by nadako** [comment]
Also, what's the supported UE version?

**Comment by parasetamon** [comment]
Thank you for a quick reply. :-)

I'm trying on 4.11.

**Comment by waneck** [comment]
Yes indeed for the latest master, the supported version is Unreal 4.11 with Haxe 3.2.1 . As for your question, take a look at https://github.com/proletariatgames/UE4Hx-Tests/blob/master/Source/HaxeUnitTests/HaxeUnitTests.Build.hx and see if that helps you. If not, feel free to reopen the issue

**Comment by waneck** [comment]
Also I plan to have a good example project and better getting started docs ready for the WWX talk

**Comment by parasetamon** [comment]
Thank you very much, I'll try your suggestion. ☺
It would be better if you add the UE4Hx-Tests link to the README.md.

by the way. Goodluck at WWX !

**Comment by nadako** [comment]
@waneck if you come to IRC, I'll annoy you about how to get started with this thing :-P

**Comment by waneck** [comment]
Thank you :)
BTW, you can ignore all the `Sys.getEnv` / `FileSystem` tests when writing your own file

**Comment by parasetamon** [comment]
Sorry to troubling you guys again.

I've successed the build.hx process. I created AMyActor.hx in the static folder and copy the example from README.md and compile it in UE4, And got this.

/AMyActor.hx:5: lines 5-23 : Unreal Glue Extension: Do not extend Unreal types on the global namespace. Use a package

here's the full log.
[fulllog.txt](https://github.com/proletariatgames/unreal.hx/files/259852/fulllog.txt)

Thank you.

**Comment by waneck** [comment]
I'm sorry, you need a package for any class that extends unreal stuff. I plan to lift that limitation soon

**Comment by parasetamon** [comment]
So I've to put it in a folder ?

**Comment by parasetamon** [comment]
Sorry. I'll try this http://old.haxe.org/ref/packages

Thank you
