### ISSUE TITLE
HotDeploy on cppia

### ISSUE THREAD

**Issue by palmalcheg** [proletariatgames/unreal.hx#42]
I was playing with 'PlatformerGame' example lately, before there was an effort to use 'haxefield' Unreal project of my own. In  both cases i failed to see the AActor - subclasses (from Haxe/Scripts dir) to be hot deployed to Unreal editor (Class view), though glue code was generated and gen-build-script.hxml succeded.

In logs there were only traces from UnrealCppia and company.

If anybody can help to clarify this behaviour - is it OK or need some more tweaks and details for setup ? Do i need full static  recompile  to see new classes in Editor ?

**Comment by waneck** [comment]
I've just realized that the documentation was ambiguous in this regard. When creating a new UObject-derived class, or when adding new uproperties/ufunctions, or changing their signature, you must perform a C++ recompilation so the type is updated. After they are updated, you can then quickly iterate the ufunction contents, or add/remove any other non-ufunction functions by compiling only cppia itself.
I've updated the documentation at https://github.com/proletariatgames/unreal.hx/wiki/Faster-compiler-iteration-with-cppia

Also note that we have plans to lift this limitation and generate the UClass types from cppia directly
