### ISSUE TITLE
Help with understanding

### ISSUE THREAD

**Issue by zulman** [proletariatgames/unreal.hx#43]
Hi guys, 

Thank you so much for this plugin, it's awesome! Would you be so kind to help me understand what is happening under the hood of Haxe compiling? As i understand Haxe is just intermediate syntax between Haxe language and c++. I mean if Haxe compiles directly to c++ why compiling time in Haxe is so short? Are we compiling C++ generated code after Haxe compilation?

Thank you, hope UE 4.12 support will be released soon. Now i have this kind of problem:

`\Plugins\UE4Haxe\Source\HaxeInit\HaxeInit.Build.cs(1404,22) : error CS0619: 'UnrealBuildTool.RulesCompiler.GetModuleFilename(string)' is obsolete: 'GetModuleFilename is deprecated, use the ModuleDirectory property on any ModuleRules instead to get a path to your module.'`

**Comment by waneck** [comment]
Hi there. Thanks for your support!
Haxe does compile to C++, and the normal compilation times are actually a bit bigger than a normal Unreal C++ project. It compiles a part of the code while compiling Haxe, and also creates a bunch of glue code that is compiled by Unreal, after Haxe compilation.
However, we support cppia, which is a virtual machine made by the same author of the C++ Haxe target. Cppia compiles in a couple of seconds at most, and allows you to achieve very fast iteration times, while allowing you to compile the final builds in C++ itself. You can read more about it at https://github.com/proletariatgames/unreal.hx/wiki/Faster-compiler-iteration-with-cppia .
Also for a cool demo of how fast it compiles when using it, you can check out this video https://www.youtube.com/v/WOK5m_D1gOc?start=3854&end=4027&version=3&autoplay=1 

As for the error, we still don't support UE 4.12, but I've opened an issue about it: https://github.com/proletariatgames/unreal.hx/issues/44 . I'll close this one, but feel free to ask more questions if you need.
