### ISSUE TITLE
Support Unreal 4.12

### ISSUE THREAD

**Issue by waneck** [proletariatgames/unreal.hx#44]
Create a system that will allow multiple unreal versions to be used with the same unreal.hx codebase

**Comment by krupin-maxim** [comment]
When will plugin support unreal 4.12 or 4.13?

**Comment by cmandlbaur** [comment]
Any news on this? 4.14 is out now. Any ideas on an approach? I'm sure you guys are busy right now with the early access release, but maybe with some direction some of might be able to help out?

**Comment by peteshand** [comment]
Any news on this?

**Comment by nitrobin** [comment]
You can checkout our fork with UE 4.14 support: https://github.com/nitrobin/HaxePlatformerGame

https://github.com/nitrobin/HaxePlatformerGame/commits/next (Fork of Unreal.hx demo adopted for UE 4.14 and Android build)
https://github.com/nitrobin/unreal.hx/commits/next (UE 4.14 amd Android support fork)
https://gist.github.com/nitrobin/65aa08c97eab2c65fe7e7fe3da4f1ad6  - patch required for UE 4.14 build system (maybe in the future will not need)

https://github.com/nitrobin/UE4HaxeExternGenerator/commits/next (litle changes for externs generator)
https://github.com/nitrobin/hxcpp/tree/unreal-android (hxcpp android toolchain for UE)

**Comment by waneck** [comment]
4.19 support is in, and 4.17 and lower support was released as 0.4.0
