### ISSUE TITLE
add support  for UMovementComponent::SlideAlongSurface,UMovementComponent::ShouldSkipUpdate, FVector::GetClampedToMaxSize

### ISSUE THREAD

**Issue by palmalcheg** [proletariatgames/unreal.hx#46]

**Comment by waneck** [comment]
Can you provide a pull request?

**Comment by palmalcheg** [comment]
Hm, maybe I need to rephrase description not  to mislead anybody =) Actually what I want is to has the named methods in appropriate classes. Or, as a workaround, somebody can point out the alternatives for those functions ?

I'm trying to complete Unreal Doc C++ tutorials, now i'm stuck  on step 
https://docs.unrealengine.com/latest/INT/Programming/Tutorials/Components/3/index.html

The proble code is at the begining of page =).

**Comment by waneck** [comment]
You should be able to do this change yourself, and submit it as a Pull Request. You can read about extern definitions at https://github.com/proletariatgames/unreal.hx/wiki/Extern-definitions , and you can see examples of how this is done by looking at the commit log. For example: https://github.com/proletariatgames/unreal.hx/commit/fc9b1a861162652e6fb5f31980892f84c7f9f35b

**Comment by palmalcheg** [comment]
Sorry for delay.

Unable to create PR because of "push" restrictions , permissions not granted =(
