### ISSUE TITLE
Error in Windows for HTML5 and Android targtets

### ISSUE THREAD

**Issue by krupin-maxim** [proletariatgames/unreal.hx#49]
I try to launch game for HTML5 and Android targets, but compilation is fail with error:

`
LogPlayLevel: UnrealBuildTool: In file included from E:\sp2\unreal\unreal_project\Source\GameProjectHaxe\Generated\Private\uhx\glues\AActor_Glue.cpp:25:
LogPlayLevel: UnrealBuildTool: In file included from E:/sp2/unreal/unreal_project/Source/GameProjectHaxe/../GameProjectHaxe/Generated/Public/uhx/glues/AActor_Glue.h:15:
LogPlayLevel: UnrealBuildTool: E:/sp2/unreal/unreal_project/Source/GameProjectHaxe/Generated/Shared\VariantPtr.h(25,10) :  error: constructor cannot be redeclared
LogPlayLevel: UnrealBuildTool:   inline VariantPtr(int inRHS) : raw((UIntPtr) inRHS) { }
LogPlayLevel: UnrealBuildTool:          ^
LogPlayLevel: UnrealBuildTool: E:/sp2/unreal/unreal_project/Source/GameProjectHaxe/Generated/Shared\VariantPtr.h(23,10) :  note: previous declaration is here
LogPlayLevel: UnrealBuildTool:   inline VariantPtr(IntPtr inRHS) : raw((UIntPtr) inRHS) { }
LogPlayLevel: UnrealBuildTool:          ^
LogPlayLevel: UnrealBuildTool: E:/sp2/unreal/unreal_project/Source/GameProjectHaxe/Generated/Shared\VariantPtr.h(25,10) :  error: redefinition of 'VariantPtr'
LogPlayLevel: UnrealBuildTool:   inline VariantPtr(int inRHS) : raw((UIntPtr) inRHS) { }
LogPlayLevel: UnrealBuildTool:          ^
LogPlayLevel: UnrealBuildTool: E:/sp2/unreal/unreal_project/Source/GameProjectHaxe/Generated/Shared\VariantPtr.h(23,10) :  note: previous definition is here
LogPlayLevel: UnrealBuildTool:   inline VariantPtr(IntPtr inRHS) : raw((UIntPtr) inRHS) { }
LogPlayLevel: UnrealBuildTool:          ^
LogPlayLevel: UnrealBuildTool: 2 errors generated.
`

**Comment by waneck** [comment]
We still haven't added support for HTML5 and Android. It shouldn't be too hard to do - just make sure we build hxcpp with the right flags for these targets.
As for this error, it's because it's expecting a 64-bit system, in which `int` and `intptr_t` are different types. If you'd like to pursue this, adding a `#ifdef` on the `int` constructor to only exist on 64-bit platforms should make the error go away.

**Comment by waneck** [comment]
I'm closing this for now. Feel free to submit a PR with the needed android/html5 changes!
