### ISSUE TITLE
Array in cppia

### ISSUE THREAD

**Issue by krupin-maxim** [proletariatgames/unreal.hx#51]
I want to work with `tink.core` in hot-reload mode. I made a class

package game;
import tink.core.*;

@:uclass
class AGameProjectGameMode extends unreal.AGameMode {

    public function new(wrapped) {
        super(wrapped);
        Future.ofMany(
            [
                futureIt(1),
                futureIt(2),
                futureIt(3)
            ]
        ).handle(function(responses){
            trace("Responses are: ", responses);
            trace("Length of responses: ", responses.length);
            trace("Iterate responses:");
            for (response in responses) {
                trace(">>>", response);
            }
        });
    }
    private function futureIt(number:Int):Future<Outcome<Int, Dynamic>> {
        var future = Future.trigger();
        future.trigger(Outcome.Success(number));
        return future;
    }
}
and put it in `Scripts` directory. Traces are:

`Responses are: ,[Success(1),Success(2),Success(3)]`
`Length of responses: ,7`
`Iterate responses:`
`>>>,Success(1)`
`>>>,Success(2)`
`>>>,Success(3)`
`>>>,null`
`>>>,null`
`>>>,null`
`>>>,null`

In `Static` path this code works correct.

 Can you help me to understand it?

**Comment by krupin-maxim** [comment]
I tested it in `haxe 3.2` with old `unreal.hx`. It worked correct in scripts.

**Comment by waneck** [comment]
This seems like a cppia bug that was recently fixed. Can you try with the
very latest haxe? You can get it from http://build.haxe.org

**Comment by krupin-maxim** [comment]
With very latest haxe I got compile-error:

     [exec] HaxeCompiler: Error: While running :g++ -I/hdd/maxim/sp2_ar/game/unreal/unreal_project/Intermediate/Haxe/Linux-Development-Editor/Static/Built/obj/linux64-stat-debug/__pch/haxe -Iinclude -I/hdd/maxim/sp2_ar/game/unreal/unreal_project/Source/GameProjectHaxe/Generated/Shared -c -fvisibility=hidden -g -fpic -fPIC -DHX_LINUX -DHXCPP_DEBUG -DSTATIC_LINK -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_SCRIPTABLE -DHXCPP_API_LEVEL=330 -m64 -DHXCPP_M64 -I/opt/haxetoolkit/haxelib/hxcpp/3,3,49/include -x c++ -frtti -Wno-invalid-offsetof ./src/unreal/inputcore/ETouchIndex_EnumConv.cpp -o/hdd/maxim/sp2_ar/game/unreal/unreal_project/Intermediate/Haxe/Linux-Development-Editor/Static/Built/obj/linux64-stat-debug/a16ab0ee_ETouchIndex_EnumConv.o
     [exec] HaxeCompiler: ./src/unreal/inputcore/ETouchIndex_EnumConv.cpp: In static member function ‘static Int unreal::inputcore::ETouchIndex_EnumConv_obj::unwrap(unreal::inputcore::ETouchIndex)’:
     [exec] HaxeCompiler: ./src/unreal/inputcore/ETouchIndex_EnumConv.cpp:80:102: error: ‘_hx_getEnumValueIndex’ was not declared in this scope
     [exec] HaxeCompiler:  HXLINE(  48)  return ::unreal::inputcore::ETouchIndex_EnumConv_obj::haxeToUe((_hx_getEnumValueIndex(v) + (int)1));
     [exec] HaxeCompiler:                                                                                                       ^
     [exec] HaxeCompiler: Error: Build failed
     [exec] Haxe compilation failed

**Comment by waneck** [comment]
You'll need the latest hxcpp as well :)

**Comment by krupin-maxim** [comment]
`Haxe Compiler 3.3.0 (git build development @ 7b1010e)`
`hxcpp: 3.3.49 [git]`

It's too sad, but bug is still here :-(

**Comment by waneck** [comment]
Which bug? `_hx_getEnumValueIndex` ?

**Comment by waneck** [comment]
Okay, I've just tested it locally and it is still a problem indeed. I've reported it at https://github.com/HaxeFoundation/haxe/issues/5515
