### ISSUE TITLE
Please accurately document hxcpp/haxe/unreal versions

### ISSUE THREAD

**Issue by Sunjammer** [proletariatgames/unreal.hx#56]
This is an incredibly interesting library doing something quite important that is prohibitively frustrating to get working. Please update the docs to reflect the creation of an actual _working_ setup, including the _exact_ versions of haxe, hxcs, hxcpp and unreal: I'm getting thematically similar but otherwise different compile errors based on various combinations of each, usually down to missing types, wrong enum values, or most recently Int not being a declared type. The example project does not build either.

I know much of this is Epic's fault with how much they love to break C++ features every update, but still.
Would love to pitch in on this one but it needs a nicer doormat. Plz 2 make Unreal fun again <3

**Comment by waneck** [comment]
Hi, thanks for the interest in unreal.hx. As said in the README, we have been developing using Haxe 3.3 and Unreal 4.11 . As an experiment, I tried to compile [HaxePlatformerGame](https://github.com/waneck/HaxePlatformerGame) from scratch using the release Haxe 3.3-rc1 compiler, and latest haxelib hxcpp/hxcs. The build was successful.

Can you be more specific on what's your test project, what versions are you using, and what errors have you been having?

**Comment by waneck** [comment]
Closing for lack of response
