### ISSUE TITLE
Crashing Editor when compile haxe-code (unreal 4.14)

### ISSUE THREAD

**Issue by krupin-maxim** [proletariatgames/unreal.hx#59]
1. Launch https://github.com/nitrobin/HaxePlatformerGame in Unreal Editor 4.14
2. Change any haxe code, for example, add trace in PlayerController.hx
3. Press "Compile" button in Editor
4. Editor crashed

I use haxe 3.3.0-rc.1, hxcpp 3.3.49

>     [exec] [2017.01.10-10.41.33:046][ 22]CompilerResultsLog: New page: Compilation - Jan 11, 2017, 1:41:33 AM
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info 
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info Running Mono...
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info 
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info /hdd/maxim/git/iceowl/ue414/Engine ~/HaxePlatformerGame/PlatformerGame
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info Using clang version '3.8.0' (string), 3 (major), 8 (minor), 0 (patch)
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info Creating makefile for hot reloading PlatformerGame (.uproject file is newer)
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info Compiling game modules for hot reload
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info BaseModuleRules.hx:45: modulePath: /home/maxim/HaxePlatformerGame/PlatformerGame/Source/PlatformerGame/PlatformerGame.Build.cs
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info BaseModuleRules.hx:46: haxeInitPath: /home/maxim/HaxePlatformerGame/PlatformerGame/Plugins/UnrealHx/Source/HaxeInit/HaxeInit.Build.cs
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info InitPlugin.hx:48: Updating game project...
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info InitPlugin.hx:50: Updating game module...
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info haxe -version
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info HaxeCompiler: 3.3.0
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info HaxeModuleRules.hx:230: baking externs
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info haxe --cwd /home/maxim/HaxePlatformerGame/PlatformerGame/Haxe -cp /home/maxim/HaxePlatformerGame/PlatformerGame/Plugins/UnrealHx/Haxe/Static -D use-rtti-doc -D bake-externs -cpp /home/maxim/HaxePlatformerGame/PlatformerGame/Haxe/Generated/Externs_Editor --no-output --macro ue4hx.internal.ExternBaker.process(["/home/maxim/HaxePlatformerGame/PlatformerGame/Plugins/UnrealHx/Haxe/Externs","/home/maxim/HaxePlatformerGame/PlatformerGame/Haxe/Externs"], false) -D WITH_EDITOR -D BUILDTOOL_VERSION_LEVEL=4
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info HaxeModuleRules.hx:265: compiling Haxe
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info haxe --cwd /home/maxim/HaxePlatformerGame/PlatformerGame/Haxe arguments.hxml -cp /home/maxim/HaxePlatformerGame/PlatformerGame/Haxe/Generated/Externs_Editor -cp /home/maxim/HaxePlatformerGame/PlatformerGame/Plugins/UnrealHx/Haxe/Static -cp /home/maxim/HaxePlatformerGame/PlatformerGame/Haxe/Static -main UnrealInit -D static_link -D destination=/home/maxim/HaxePlatformerGame/PlatformerGame/Intermediate/Haxe/Linux-Development-Editor/libhaxeruntime.a -D haxe_runtime_dir=/home/maxim/HaxePlatformerGame/PlatformerGame/Source/PlatformerGame -D bake_dir=/home/maxim/HaxePlatformerGame/PlatformerGame/Haxe/Generated/Externs_Editor -D HXCPP_DLL_EXPORT -cpp /home/maxim/HaxePlatformerGame/PlatformerGame/Intermediate/Haxe/Linux-Development-Editor/Static/Built --macro ue4hx.internal.CreateGlue.run(["/home/maxim/HaxePlatformerGame/PlatformerGame/Haxe/Static"], ["/home/maxim/HaxePlatformerGame/PlatformerGame/Haxe/Scripts"]) -D WITH_EDITOR -dce no -debug -D HXCPP_M64 -D scriptable -D WITH_CPPIA -D BUILDTOOL_VERSION_LEVEL=4
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info haxelib run hxcpp Build.xml haxe -Ddebug -DBUILDTOOL_VERSION_LEVEL="4" -DHXCPP_DLL_EXPORT="1" -DHXCPP_M64="1" -DWITH_CPPIA="1" -DWITH_EDITOR="1" -Dbake_dir="/home/maxim/HaxePlatformerGame/PlatformerGame/Haxe/Generated/Externs_Editor" -Ddestination="/home/maxim/HaxePlatformerGame/PlatformerGame/Intermediate/Haxe/Linux-Development-Editor/libhaxeruntime.a" -Dhaxe3="1" -Dhaxe_runtime_dir="/home/maxim/HaxePlatformerGame/PlatformerGame/Source/PlatformerGame" -Dhaxe_ver="3.3" -Dhxcpp_api_level="330" -Dscriptable="1" -Dsource-header="Generated by Haxe 3.3.0" -Dstatic_link="1" -I"/home/maxim/HaxePlatformerGame/PlatformerGame/Haxe/Scripts/" -I"/home/maxim/HaxePlatformerGame/PlatformerGame/Haxe/Static/" -I"/home/maxim/HaxePlatformerGame/PlatformerGame/Plugins/UnrealHx/Haxe/Static/" -I"/home/maxim/HaxePlatformerGame/PlatformerGame/Haxe/Generated/Externs_Editor/" -I"" -I"./" -I"/" -I"/opt/haxetoolkit/linux64/haxe/std/cpp/_std/" -I"/opt/haxetoolkit/linux64/haxe/std/"
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info Creating /home/maxim/HaxePlatformerGame/PlatformerGame/Intermediate/Haxe/Linux-Development-Editor/Static/Built/obj/linux64-stat-debug/__pch/haxe/hxcpp.h.gch...
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info  - Compiling group 'haxe' with flags -Iinclude -I/home/maxim/HaxePlatformerGame/PlatformerGame/Source/PlatformerGame/Generated/Shared -c -fvisibility=hidden -g -fpic -fPIC -DHX_LINUX -DHXCPP_DEBUG -DSTATIC_LINK(static) -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHXCPP_SCRIPTABLE(haxe) -DHXCPP_API_LEVEL=330(haxe) -m64 -DHXCPP_M64 -I/opt/haxetoolkit/haxelib/hxcpp/3,3,49/include tags=[haxe,static]
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info  - Compile : src/uhx/glues/PlayerController_GlueScript.cpp
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info  - Compile : src/uhx/expose/PlayerController_Expose.cpp
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info  clean libUnrealInit-debug.a
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info  - Link : libUnrealInit-debug.a
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info  - Ranlib : libUnrealInit-debug.a
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info haxe --cwd /home/maxim/HaxePlatformerGame/PlatformerGame/Haxe arguments.hxml -cp /home/maxim/HaxePlatformerGame/PlatformerGame/Haxe/Generated/Externs_Editor -cp /home/maxim/HaxePlatformerGame/PlatformerGame/Plugins/UnrealHx/Haxe/Static -cp /home/maxim/HaxePlatformerGame/PlatformerGame/Haxe/Static -cp /home/maxim/HaxePlatformerGame/PlatformerGame/Haxe/Scripts -main UnrealCppia -D cppia -D ustatic_target=/home/maxim/HaxePlatformerGame/PlatformerGame/Intermediate/Haxe/Linux-Development-Editor/Static/Built -cpp /home/maxim/HaxePlatformerGame/PlatformerGame/Binaries/Haxe/game.cppia --macro ue4hx.internal.CreateCppia.run(["/home/maxim/HaxePlatformerGame/PlatformerGame/Haxe/Static"], ["/home/maxim/HaxePlatformerGame/PlatformerGame/Haxe/Scripts"],null) -debug -D WITH_EDITOR -D BUILDTOOL_VERSION_LEVEL=4
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info BaseModuleRules.hx:45: modulePath: /home/maxim/HaxePlatformerGame/PlatformerGame/Source/PlatformerGame/HaxeExternalModule.Build.cs
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info BaseModuleRules.hx:46: haxeInitPath: /home/maxim/HaxePlatformerGame/PlatformerGame/Plugins/UnrealHx/Source/HaxeInit/HaxeInit.Build.cs
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info @progress push 5%
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info @progress 'Generating code...' 0%
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info @progress 'Generating code...' 67%
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info @progress 'Generating code...' 100%
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info @progress pop
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info Using bundled libc++ standard C++ library.
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info @progress 'Compiling C++ source files...' 0%
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info Performing 3 actions (8 in parallel)
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info @progress 'Compiling C++ source code...' 0%
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info [2/3] Link libUE4Editor-PlatformerGameLoadingScreen-8539.so
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info [1/3] Compile Module.PlatformerGame.1_of_8.cpp
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info @progress 'Compiling C++ source code...' 25%
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info @progress 'Compiling C++ source code...' 50%
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info [3/3] Link libUE4Editor-PlatformerGame-2306.so
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info @progress 'Compiling C++ source code...' 75%
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info Total build time: 53.38 seconds
>     [exec] [2017.01.10-10.41.33:047][ 22]CompilerResultsLog: Info HaxeModuleRules.hx:159: Touching /home/maxim/HaxePlatformerGame/PlatformerGame/PlatformerGame.uproject
>     [exec] [2017.01.10-10.41.33:047][ 22]LogMainFrame: MainFrame: Module compiling took 53.552 seconds
>     [exec] [2017.01.10-10.41.33:125][ 22]HaxeLog: UnrealInit.hx:24: initializing unreal haxe
>     [exec] [2017.01.10-10.41.33:125][ 22]HaxeLog: UnrealInit.hx:70: loading cppia
>     [exec] [2017.01.10-10.41.33:136][ 22]HaxeLog: UnrealCppia.hx:3: initializing unreal cppia script
>     [exec] [2017.01.10-10.41.33:136][ 22]HaxeLog: UnrealInit.hx:75: Setting cppia live reload types
>     [exec] [2017.01.10-10.41.33:145][ 22]LogClass: EGameState HotReload.
>     [exec] [2017.01.10-10.41.33:177][ 22]LogContentBrowser: Native class hierarchy updated for 'PlatformerGame' in 0.0265 seconds. Added 12 classes and 7 folders.
>     [exec] [2017.01.10-10.41.33:177][ 22]Module being reloaded does not support dynamic unloading -- abandoning existing loaded module so that we can load the recompiled version!
>     [exec] terminating with uncaught exception of type Dynamic
>     [exec] Signal 6 caught.
>     [exec] Malloc Size=131076 LargeMemoryPoolOffset=131092 
>     [exec] Malloc Size=65535 LargeMemoryPoolOffset=196655 
>     [exec] Malloc Size=556026 LargeMemoryPoolOffset=752698 
>     [exec] [2017.01.10-10.41.33:213][ 22]Display: HotReload successful (21 functions remapped  1 scriptstructs remapped)
>     [exec] CommonLinuxCrashHandler: Signal=6
>     [exec] Using binned.
>     [exec] LogPlatformFile: Not using cached read wrapper
>     [exec] LogInit:Display: RandInit(548487015) SRandInit(548487015).
>     [exec] LogTaskGraph: Started task graph with 4 named threads and 7 total threads with 1 sets of task threads.
>     [exec] LogInit: Build: ++UE4+Release-4.14-CL-0
>     [exec] LogInit: Engine Version: 4.14.2-0+++UE4+Release-4.14
>     [exec] LogInit: Compatible Engine Version: 4.14.0-0+++UE4+Release-4.14
>     [exec] LogInit: Net CL: 0
>     [exec] LogInit: Compiled (64-bit): Jan  9 2017 17:23:42
>     [exec] LogInit: Compiled with Clang: 3.8.0 (tags/RELEASE_380/final)
>     [exec] LogInit: Build Configuration: Shipping
>     [exec] LogInit: Branch Name: ++UE4+Release-4.14
>     [exec] LogInit: Command line:  -Abslog=/home/maxim/HaxePlatformerGame/PlatformerGame/Saved/Logs/PlatformerGame-CRC.log /home/maxim/HaxePlatformerGame/PlatformerGame/Saved/Crashes/crashinfo-PlatformerGame-pid-6600-7A11C60A2101110A002900EA20A7DF47/
>     [exec] LogInit: Base directory: /hdd/maxim/git/iceowl/ue414/Engine/Binaries/Linux/
>     [exec] LogInit: Installed Engine Build: 1
>     [exec] LogInit: Presizing for max 100000 objects, including 0 objects not considered by GC, pre-allocating 0 bytes for permanent pool.
>     [exec] LogInit: Object subsystem initialized
>     [exec] [2017.01.10-10.41.33:328][  0]LogInit: Linux hardware info:
>     [exec] [2017.01.10-10.41.33:328][  0]LogInit:  - we are the first instance of this executable
>     [exec] [2017.01.10-10.41.33:328][  0]LogInit:  - this process' id (pid) is 10872, parent process' id (ppid) is 6600
>     [exec] [2017.01.10-10.41.33:328][  0]LogInit:  - we are not running under debugger
>     [exec] [2017.01.10-10.41.33:328][  0]LogInit:  - machine network name is 'maxim'
>     [exec] [2017.01.10-10.41.33:328][  0]LogInit:  - user name is 'maxim' (maxim)
>     [exec] [2017.01.10-10.41.33:328][  0]LogInit:  - we're logged in locally
>     [exec] [2017.01.10-10.41.33:328][  0]LogInit:  - we're running with rendering
>     [exec] [2017.01.10-10.41.33:328][  0]LogInit:  - CPU: GenuineIntel 'Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz' (signature: 0x306C3)
>     [exec] [2017.01.10-10.41.33:328][  0]LogInit:  - Number of physical cores available for the process: 4
>     [exec] [2017.01.10-10.41.33:328][  0]LogInit:  - Number of logical cores available for the process: 8
>     [exec] [2017.01.10-10.41.33:328][  0]LogInit:  - Cache line size: 64
>     [exec] [2017.01.10-10.41.33:328][  0]LogInit:  - Memory allocator used: binned
>     [exec] [2017.01.10-10.41.33:328][  0]LogLinux: Skipped benchmarking clocks because the engine is running in a standalone program mode - CLOCK_REALTIME will be used.
>     [exec] [2017.01.10-10.41.33:328][  0]LogInit: Linux-specific commandline switches:
>     [exec] [2017.01.10-10.41.33:328][  0]LogInit:  -nodwarf (currently OFF): suppress parsing of DWARF debug info (callstacks will be generated faster, but won't have line numbers)
>     [exec] [2017.01.10-10.41.33:328][  0]LogInit:  -ansimalloc - use malloc()/free() from libc (useful for tools like valgrind and electric fence)
>     [exec] [2017.01.10-10.41.33:328][  0]LogInit:  -jemalloc - use jemalloc for all memory allocation
>     [exec] [2017.01.10-10.41.33:328][  0]LogInit:  -binnedmalloc - use binned malloc  for all memory allocation
>     [exec] [2017.01.10-10.41.33:328][  0]LogInit:  -httpproxy=ADDRESS:PORT - redirects HTTP requests to a proxy (only supported if compiled with libcurl)
>     [exec] [2017.01.10-10.41.33:328][  0]LogInit:  -reuseconn - allow libcurl to reuse HTTP connections (only matters if compiled with libcurl)
>     [exec] [2017.01.10-10.41.33:328][  0]LogInit:  -virtmemkb=NUMBER - sets process virtual memory (address space) limit (overrides VirtualMemoryLimitInKB value from .ini)
>     [exec] [2017.01.10-10.41.33:328][  0]LogInit:  - Physical RAM available (not considering process quota): 16 GB (15983 MB, 16366848 KB, 16759652352 bytes)
>     [exec] [2017.01.10-10.41.33:328][  0]LogUObjectArray: 141 objects as part of root set at end of initial load.
>     [exec] [2017.01.10-10.41.33:328][  0]LogUObjectAllocator: 23664 out of 0 bytes used by permanent object pool.
>     [exec] [2017.01.10-10.41.33:328][  0]LogUObjectArray: CloseDisregardForGC: 0/0 objects in disregard for GC pool
>     [exec] [2017.01.10-10.41.33:328][  0]LogTextLocalizationManager: No translations for ('') exist, falling back to 'en' for localization and internationalization data.
>     [exec] [2017.01.10-10.41.33:330][  0]CrashReportClientLog: CrashReportClientVersion=1.0
>     [exec] [2017.01.10-10.41.33:330][  0]CrashReportClientLog: CrashReportReceiver disabled
>     [exec] [2017.01.10-10.41.33:330][  0]CrashReportClientLog: DataRouterUrl: https://datarouter.ol.epicgames.com/datarouter/api/v1/public/data
>     [exec] [2017.01.10-10.41.33:330][  0]LogQoSReporter:Error: QoS API server is not configured, no QoS metrics will be reported.
>     [exec] [2017.01.10-10.41.33:330][  0]LogQoSReporter: QoSReporter initialized (InstanceId = '00048D092101110A0029014A20B29A00', SystemId = '2a5d5f96ef9147c0b35535562b32d0ff')
>     [exec] [2017.01.10-10.41.33:330][  0]LogQoSReporter: APIKey = 'CrashReportClient.Release'. APIServer = ''. AppVersion = 'UE4-CL-0'. AppEnvironment = 'Release'
>     [exec] [2017.01.10-10.41.33:330][  0]LogQoSReporter: QoSReporter has been configured without a valid deployment name.
>     [exec] [2017.01.10-10.41.33:330][  0]LogQoSReporter: QoSReporter has been configured without a valid deployment name.
>     [exec] [2017.01.10-10.41.33:330][  0]CrashReportClientLog: Initial state = Unknown UploadState value
>     [exec] [2017.01.10-10.41.33:330][  0]CrashReportClientLog: Initial state = Unknown UploadState value
>     [exec] [2017.01.10-10.41.33:331][  0]LogCrashDebugHelper: DepotName: //UE4/Release-4.14
>     [exec] [2017.01.10-10.41.33:331][  0]LogCrashDebugHelper: BuiltFromCL: 0
>     [exec] [2017.01.10-10.41.33:331][  0]LogCrashDebugHelper: EngineVersion: 4.14.2-0+++UE4+Release-4.14
>     [exec] [2017.01.10-10.41.33:331][  0]LogCrashDebugHelper: BuildVersion: ++UE4+Release-4.14-CL-0
>     [exec] [2017.01.10-10.41.33:331][  0]LogCrashDebugHelper:Warning: CrashDebugHelperConfig invalid
>     [exec] [2017.01.10-10.41.33:331][  0]LogCrashDebugHelper:Warning: PDB Cache disabled
>     [exec] [2017.01.10-10.41.34:300][  0]CrashReportClientLog: Got 5 pending files to upload from 'crashinfo-PlatformerGame-pid-6600-7A11C60A2101110A002900EA20A7DF47'
>     [exec] [2017.01.10-10.41.34:300][  0]CrashReportClientLog: State change from Ready to SendingFiles
>     [exec] [2017.01.10-10.41.34:300][  0]CrashReportClientLog: CompressAndSendData have 5 pending files
>     [exec] [2017.01.10-10.41.34:300][  0]CrashReportClientLog: CompressAndSendData compressing 556026 bytes ('/home/maxim/HaxePlatformerGame/PlatformerGame/Saved/Crashes/crashinfo-PlatformerGame-pid-6600-7A11C60A2101110A002900EA20A7DF47/PlatformerGame.log')
>     [exec] [2017.01.10-10.41.34:300][  0]CrashReportClientLog: CompressAndSendData compressing 1933 bytes ('/home/maxim/HaxePlatformerGame/PlatformerGame/Saved/Crashes/crashinfo-PlatformerGame-pid-6600-7A11C60A2101110A002900EA20A7DF47/wermeta.xml')
>     [exec] [2017.01.10-10.41.34:301][  0]CrashReportClientLog: CompressAndSendData compressing 2898 bytes ('/home/maxim/HaxePlatformerGame/PlatformerGame/Saved/Crashes/crashinfo-PlatformerGame-pid-6600-7A11C60A2101110A002900EA20A7DF47/Diagnostics.txt')
>     [exec] [2017.01.10-10.41.34:301][  0]CrashReportClientLog: CompressAndSendData compressing 4 bytes ('/home/maxim/HaxePlatformerGame/PlatformerGame/Saved/Crashes/crashinfo-PlatformerGame-pid-6600-7A11C60A2101110A002900EA20A7DF47/minidump.dmp')
>     [exec] [2017.01.10-10.41.34:301][  0]CrashReportClientLog: CompressAndSendData compressing 85 bytes ('/home/maxim/HaxePlatformerGame/PlatformerGame/Saved/Crashes/crashinfo-PlatformerGame-pid-6600-7A11C60A2101110A002900EA20A7DF47/CrashReportClient.ini')
>     [exec] [2017.01.10-10.41.34:316][  0]LogInit: Using libcurl 7.46.0
>     [exec] [2017.01.10-10.41.34:316][  0]LogInit:  - built for x86_64-pc-linux-gnu
>     [exec] [2017.01.10-10.41.34:316][  0]LogInit:  - supports SSL with OpenSSL/1.0.2d
>     [exec] [2017.01.10-10.41.34:316][  0]LogInit:  - supports HTTP deflate (compression) using libz 1.2.8
>     [exec] [2017.01.10-10.41.34:316][  0]LogInit:  - other features:
>     [exec] [2017.01.10-10.41.34:316][  0]LogInit:      CURL_VERSION_SSL
>     [exec] [2017.01.10-10.41.34:317][  0]LogInit:      CURL_VERSION_LIBZ
>     [exec] [2017.01.10-10.41.34:317][  0]LogInit:      CURL_VERSION_IPV6
>     [exec] [2017.01.10-10.41.34:317][  0]LogInit:      CURL_VERSION_ASYNCHDNS
>     [exec] [2017.01.10-10.41.34:317][  0]LogInit:      CURL_VERSION_LARGEFILE
>     [exec] [2017.01.10-10.41.34:317][  0]LogInit:      CURL_VERSION_TLSAUTH_SRP
>     [exec] [2017.01.10-10.41.34:317][  0]LogInit:  Libcurl: checking if '/etc/pki/tls/certs/ca-bundle.crt' exists
>     [exec] [2017.01.10-10.41.34:317][  0]LogInit:  Libcurl: checking if '/etc/ssl/certs/ca-certificates.crt' exists
>     [exec] [2017.01.10-10.41.34:317][  0]LogInit:  CurlRequestOptions (configurable via config and command line):
>     [exec] [2017.01.10-10.41.34:317][  0]LogInit:  - bVerifyPeer = true  - Libcurl will verify peer certificate
>     [exec] [2017.01.10-10.41.34:317][  0]LogInit:  - bUseHttpProxy = false  - Libcurl will NOT use HTTP proxy
>     [exec] [2017.01.10-10.41.34:317][  0]LogInit:  - bDontReuseConnections = false  - Libcurl will reuse connections
>     [exec] [2017.01.10-10.41.34:317][  0]LogInit:  - CertBundlePath = /etc/ssl/certs/ca-certificates.crt  - Libcurl will set CURLOPT_CAINFO to it
>     [exec] [2017.01.10-10.41.34:317][  0]CrashReportClientLog: Sending HTTP request: https://datarouter.ol.epicgames.com/datarouter/api/v1/public/data?AppID=CrashReporter&AppVersion=4.14.2-0%2B%2B%2BUE4%2BRelease-4.14&AppEnvironment=Release&UploadType=crashreports&UserID=000353d20e080f150002012725704178%7C%7C2a5d5f96ef9147c0b35535562b32d0ff
>     [exec] [2017.01.10-10.41.35:769][  0]CrashReportClientLog: OnProcessRequestComplete(), State=SendingFiles bSucceeded=1
>     [exec] [2017.01.10-10.41.35:769][  0]CrashReportClientLog: State change from SendingFiles to SendingFiles
>     [exec] [2017.01.10-10.41.35:769][  0]CrashReportClientLog: All uploads done
>     [exec] [2017.01.10-10.41.35:769][  0]CrashReportClientLog: State change from SendingFiles to Finished
>     [exec] [2017.01.10-10.41.36:304][  0]LogLinux: FLinuxPlatformMisc::RequestExit(0)
>     [exec] [2017.01.10-10.41.36:304][  0]LogGenericPlatformMisc: FPlatformMisc::RequestExit(0)
>     [exec] [2017.01.10-10.41.36:337][  0]CrashReportClientLog: Final state (Receiver) = Finished
>     [exec] [2017.01.10-10.41.36:337][  0]CrashReportClientLog: Final state (Receiver) = Unknown UploadState value
>     [exec] [2017.01.10-10.41.36:337][  0]LogExit: Preparing to exit.
>     [exec] [2017.01.10-10.41.36:338][  0]LogObj: Freed 0b from 0 cluster array pools.
>     [exec] [2017.01.10-10.41.36:338][  0]LogExit: Object subsystem successfully closed.
>     [exec] [2017.01.10-10.41.36:356][  0]LogModuleManager: Shutting down and abandoning module HTTP (5)
>     [exec] [2017.01.10-10.41.36:356][  0]LogModuleManager: Shutting down and abandoning module CrashDebugHelper (4)
>     [exec] [2017.01.10-10.41.36:356][  0]LogModuleManager: Shutting down and abandoning module QoSReporter (3)
>     [exec] [2017.01.10-10.41.36:356][  0]LogModuleManager: Shutting down and abandoning module Analytics (2)
>     [exec] [2017.01.10-10.41.36:356][  0]LogModuleManager: Shutting down and abandoning module CoreUObject (1)
>     [exec] [2017.01.10-10.41.36:356][  0]LogExit: Exiting.
>     [exec] Engine crash handling finished; re-raising signal 6 for the default handler. Good bye.
>
>BUILD FAILED
>/home/maxim/HaxePlatformerGame/PlatformerGame/build.xml:125: The following error occurred while executing this line:
>/home/maxim/HaxePlatformerGame/PlatformerGame/build.xml:43: exec returned: 134
>
>Total time: 8 minutes 49 seconds
>maxim@maxim ~/HaxePlatformerGame/PlatformerGame $

**Comment by krupin-maxim** [comment]
Also, I cannot package game for linux:

>UATHelper: Packaging (Linux): UnrealBuildTool: [258/258] Link PlatformerGame
>UATHelper: Packaging (Linux): UnrealBuildTool: /home/maxim/HaxePlatformerGame/PlatformerGame/Intermediate/Haxe/Linux-Development/libhaxeruntime.a(5370fa6a_CFFI.o): In function `hxcpp_kind_share(int&, char const*)':
>UATHelper: Packaging (Linux): UnrealBuildTool: /opt/haxetoolkit/haxelib/hxcpp/3,3,49/src/hx/CFFI.cpp:128: undefined reference to `std::allocator<char>::allocator()'
>UATHelper: Packaging (Linux): UnrealBuildTool: /opt/haxetoolkit/haxelib/hxcpp/3,3,49/src/hx/CFFI.cpp:128: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
>UATHelper: Packaging (Linux): UnrealBuildTool: /opt/haxetoolkit/haxelib/hxcpp/3,3,49/src/hx/CFFI.cpp:128: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
>UATHelper: Packaging (Linux): UnrealBuildTool: /opt/haxetoolkit/haxelib/hxcpp/3,3,49/src/hx/CFFI.cpp:128: undefined reference to `std::allocator<char>::~allocator()'
>UATHelper: Packaging (Linux): UnrealBuildTool: /opt/haxetoolkit/haxelib/hxcpp/3,3,49/src/hx/CFFI.cpp:132: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(char const*)'
>UATHelper: Packaging (Linux): UnrealBuildTool: /opt/haxetoolkit/haxelib/hxcpp/3,3,49/src/hx/CFFI.cpp:128: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
>UATHelper: Packaging (Linux): UnrealBuildTool: /opt/haxetoolkit/haxelib/hxcpp/3,3,49/src/hx/CFFI.cpp:128: undefined reference to `std::allocator<char>::~allocator()'
>UATHelper: Packaging (Linux): UnrealBuildTool: /home/maxim/HaxePlatformerGame/PlatformerGame/Intermediate/Haxe/Linux-Development/libhaxeruntime.a(5370fa6a_CFFI.o): In function `__hxcpp_get_kind(Dynamic)':
>UATHelper: Packaging (Linux): UnrealBuildTool: /opt/haxetoolkit/haxelib/hxcpp/3,3,49/src/hx/CFFI.cpp:145: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::size() const'
>UATHelper: Packaging (Linux): UnrealBuildTool: /opt/haxetoolkit/haxelib/hxcpp/3,3,49/src/hx/CFFI.cpp:145: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::c_str() const'
>UATHelper: Packaging (Linux): UnrealBuildTool: /home/maxim/HaxePlatformerGame/PlatformerGame/Intermediate/Haxe/Linux-Development/libhaxeruntime.a(5370fa6a_CFFI.o): In function `std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int>::~pair()':
>UATHelper: Packaging (Linux): UnrealBuildTool: /usr/include/c++/5/bits/stl_pair.h:96: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
>UATHelper: Packaging (Linux): UnrealBuildTool: /home/maxim/HaxePlatformerGame/PlatformerGame/Intermediate/Haxe/Linux-Development/libhaxeruntime.a(5370fa6a_CFFI.o): In function `std::pair<int const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::~pair()':
>UATHelper: Packaging (Linux): UnrealBuildTool: /usr/include/c++/5/bits/stl_pair.h:96: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'

Full log: https://www.dropbox.com/s/bvsrse7if6sr41x/pack_linux_ue414.log?dl=0

**Comment by waneck** [comment]
Can you try again? The Linux issues should be fixed on the ue4.14 branch, with Haxe 3.4 . Thanks!

**Comment by waneck** [comment]
Closing for lack of response
