### ISSUE TITLE
UE4.14 working yet?

### ISSUE THREAD

**Issue by datee** [proletariatgames/unreal.hx#62]
Trying to get the 4.14 branch working but running into errors.
(Other projects not using unreal.hx compiles normaly)
Is 4.14 support working at this point?

Setup:
**Windows 10**
**Visual Studio 2015**
**Unreal4.13.3-Release**
**Haxe 3.3.0-rc1**
**Hxcs 3.4.0**
**Hxcpp 3.4.49 (also tried 3.3.49, 3.4.2)**
**Unreal.hx [ue4.14 branch] [ad65c5f8c66387a294e55cae425cb9e7177780cf](https://github.com/proletariatgames/unreal.hx/tree/ad65c5f8c66387a294e55cae425cb9e7177780cf)**

`Performing 6 actions (4 in parallel)`
`Module.UnrealHxTest4.1_of_8.cpp`
`Module.UnrealHxTest4.6_of_8.cpp`
`Module.UnrealHxTest4.2_of_8.cpp`
`Module.UnrealHxTest4.7_of_8.cpp`
`G:\Unreal\projects\UnrealHxTest4\Source\UnrealHxTest4\Generated\Private\uhx\glues\EDecalBlendMode_Glue.cpp(71): error C2065: 'DBM_PostLighting': undeclared identifier`
`G:\Unreal\projects\UnrealHxTest4\Source\UnrealHxTest4\Generated\Private\uhx\glues\EDecalBlendMode_Glue.cpp(71): error C2131: expression did not evaluate to a constant`
`G:\Unreal\projects\UnrealHxTest4\Source\UnrealHxTest4\Generated\Private\uhx\glues\EDecalBlendMode_Glue.cpp(71): note: failure was caused by non-constant arguments or reference to a non-constant symbol`
`G:\Unreal\projects\UnrealHxTest4\Source\UnrealHxTest4\Generated\Private\uhx\glues\EDecalBlendMode_Glue.cpp(71): note: see usage of 'DBM_PostLighting'`
`G:\Unreal\projects\UnrealHxTest4\Source\UnrealHxTest4\Generated\Private\uhx\glues\EDecalBlendMode_Glue.cpp(71): error C2051: case expression not constant`
`G:\Unreal\projects\UnrealHxTest4\Source\UnrealHxTest4\Generated\Private\uhx\glues\EDecalBlendMode_Glue.cpp(103): error C2065: 'DBM_PostLighting': undeclared identifier`
`G:\Unreal\projects\UnrealHxTest4\Source\UnrealHxTest4\Generated\Private\uhx\glues\ULocalPlayer_Glue.cpp(38): fatal error C1083: Cannot open include file: 'OnlineSubsystemTypes.h': No such file or directory
Module.UnrealHxTest4.5_of_8.cpp`
`G:\Unreal\projects\UnrealHxTest4\Source\UnrealHxTest4\Generated\Private\uhx\glues\AGameModeBase_Glue.cpp(324): error C2568: '->*': unable to resolve function overload`
`G:\Unreal\projects\UnrealHxTest4\Source\UnrealHxTest4\Generated\Private\uhx\glues\AGameModeBase_Glue.cpp(324): note: could be 'FString AGameModeBase::InitNewPlayer(APlayerController *,const TSharedPtr<const FUniqueNetId,0> &,const FString &,const FString &)'`
`G:\Unreal\projects\UnrealHxTest4\Source\UnrealHxTest4\Generated\Private\uhx\glues\AGameModeBase_Glue.cpp(324): note: or       'FString AGameModeBase::InitNewPlayer(APlayerController *,const FUniqueNetIdRepl &,const FString &,const FString &)'`
`G:\Unreal\projects\UnrealHxTest4\Source\UnrealHxTest4\Generated\Private\uhx\glues\IOnlinePlatformData_Glue.cpp(26): fatal error C1083: Cannot open include file: 'OnlineSubsystemTypes.h': No such file or directory`
`G:\Unreal\projects\UnrealHxTest4\Source\UnrealHxTest4\Generated\Private\uhx\glues\UInputComponent_Glue.cpp(47): error C2664: 'FInputActionBinding &UInputComponent::GetActionBinding(const int32)': cannot convert argument 1 from 'FName' to 'const int32'`
`G:\Unreal\projects\UnrealHxTest4\Source\UnrealHxTest4\Generated\Private\uhx\glues\UInputComponent_Glue.cpp(47): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called`
`ERROR : UBT error : Failed to produce item: G:\Unreal\projects\UnrealHxTest4\Binaries\Win64\UE4Editor-UnrealHxTest4.pdb`

**Comment by waneck** [comment]
Could you try now?

**Comment by zaynyatyi** [comment]
Tried to compile on mac now
`Info HaxeModuleRules.hx:159: Touching /Users/pro13/dev/UE4_workshop/HaxeTest_0/HaxeTest_0.uproject
Info Compiling group: haxe
Info xcrun --sdk macosx clang++ -Iinclude -I/Users/pro13/dev/UE4_workshop/HaxeTest_0/Source/HaxeTest_0/Generated/Shared -c -fvisibility=hidden -stdlib=libc++ -Qunused-arguments -g -I/Users/pro13/dev_tools/haxe/lib/hxcpp/3,4,64/include -DHX_MACOS -m64 -Wno-parentheses -Wno-null-dereference -Wno-unused-value -Wno-format-extra-args -Wno-bool-conversion -DHXCPP_DEBUG -DSTATIC_LINK(static) -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHXCPP_SCRIPTABLE(haxe) -DHXCPP_API_LEVEL=331(haxe) ... tags=[haxe,static]
Info  - src/unreal/_TArrayImpl/TArrayImpl_Impl_.cpp
Info  - src/unreal/_TArray/TArray_Impl_.cpp
Info HaxeCompiler: Error: ./src/unreal/_TArrayImpl/TArrayImpl_Impl_.cpp:116:36: error: member reference type '::uhx::glues::TArrayImpl_Glue' (aka 'uhx::glues::TArrayImpl_Glue_obj') is not a pointer; did you mean to use '.'?
Info HaxeCompiler: HXDLIN(  74)            (*(thisDataPointer1))->set_Item(this1,index,::unreal::helpers::HaxeHelpers_obj::variantToPointer(val));
Info HaxeCompiler:                         ~~~~~~~~~~~~~~~~~~~~~^~
Info HaxeCompiler:                                              .
Info HaxeCompiler: ./src/unreal/_TArrayImpl/TArrayImpl_Impl_.cpp:141:36: error: member reference type '::uhx::glues::TArrayImpl_Glue' (aka 'uhx::glues::TArrayImpl_Glue_obj') is not a pointer; did you mean to use '.'?
Info HaxeCompiler: HXDLIN(  98)            (*(thisDataPointer1))->Push(this1,::unreal::helpers::HaxeHelpers_obj::variantToPointer(obj));
Info HaxeCompiler:                         ~~~~~~~~~~~~~~~~~~~~~^~
Info HaxeCompiler:                                              .
Info HaxeCompiler: ./src/unreal/_TArrayImpl/TArrayImpl_Impl_.cpp:178:43: error: member reference type '::uhx::glues::TArrayImpl_Glue' (aka 'uhx::glues::TArrayImpl_Glue_obj') is not a pointer; did you mean to use '.'?
Info HaxeCompiler: HXDLIN( 134)            return (*(thisDataPointer1))->Insert(this1,::unreal::helpers::HaxeHelpers_obj::variantToPointer(item),index);
Info HaxeCompiler:                                ~~~~~~~~~~~~~~~~~~~~~^~
Info HaxeCompiler:                                                     .
Info HaxeCompiler: 3 errors generated.
Info HaxeCompiler: Error: Build failed
Info Haxe compilation failed
`
Got that error.
UE4 version is 4.14.3
haxe 3.4.2
hxcpp: [3.4.64]
hxcs: [3.4.0]
unreal.hx commit 2f51bd6a6bde367818124a0174bd0582265628a7

**Comment by zaynyatyi** [comment]
Btw it's alright with haxe 3.4.0

**Comment by waneck** [comment]
This should be fixed on the latest ue4.14 branch. Please let me know if you run into any other issues
