### ISSUE TITLE
UE4.16 Plugin Setup?

### ISSUE THREAD

**Issue by jrgalim** [proletariatgames/unreal.hx#66]
I'm attempting to get the ue4.16 branch up and running with a bare-bones project, and I have run into a couple problems.  I've cloned/checked out that branch, and ran **init-plugin.hxml**.  At first I got an "invalid excape sequence" error, which related to the **gameDir** string that was generated (which had backslashes in it).  I remedied this by adding `gameDir = gameDir.replace('\\','/');` at line 85 in **InitPlugin.hx**, but then I get the following error:
`c:\HaxeToolkit\haxe\std/haxe/macro/Context.hx:247: charactes 9-32:Type not found 'HaxeModuleRules' (called from ../unreal.hx/Haxe/BuildTool/Package.hx:42`

Is the 4.16 branch missing some files?

**Comment by waneck** [comment]
Thanks for the bug report. This was an oversight as we are moving away from having to define your own Build.hx file - now you can directly subclass `HaxeModuleRules` on the Build.cs, in C# itself (and init-plugin.hxml won't be needed anymore). We still need to fix this for people that will use Build.hx, but a simple workaround would be to use Build.cs directly - like in https://github.com/proletariatgames/UE4Hx-Tests/blob/ue4.16/Source/HaxeUnitTests/HaxeUnitTests.Build.cs#L3

**Comment by jrgalim** [comment]
Well that sounds wonderful.  So once I check out ue4.16 and modify Build.cs to extend `HaxeModuleRules`, I can go straight into adding classes to Haxe/Scripts?  Or is there another step before the engine will recognize my haxe class files and compile them?

**Comment by waneck** [comment]
Once you check out ue4.16, just change your Build.cs file to subclass `HaxeModuleRules`, and add the `UnrealHx` plugin to your uproject - e.g.
```
"Plugins": [{ "Name": "UnrealHx", "Enabled": true }]
```

**Comment by jrgalim** [comment]
Sorry I'm new to plugins, but what file does that get added to?  My .uproject file directly?

**Comment by waneck** [comment]
Yes, so your project's `.uproject` file will have that. E.g.:

```
{
"FileVersion": 3,
...
"Modules": [ ... ],
"Plugins": [{ "Name": "UnrealHx", "Enabled": true }]
}
```

**Comment by jrgalim** [comment]
Ok, so close.  My test haxe class compiles, but I'm seeing another compile errors in the editor.  First, there's a note about unity builds:

> If you are compiling with unity builds, please make sure to set `forceHaxeCompilation` to true, as the pre-build scripts are not compatible with unity builds

Where do I set this flag, or where do I disable unity builds?

The error I get now says:
> `ERROR: 'C:/Users/Jamie/Dropbox/RooVR/Intermediate/Build/Win64/UE4Editor/Inc/RooVR/CallHelper.generated.h': Changes to generated code are not allowed - conflicts written to 'C:/Users/Jamie/Dropbox/RooVR/Intermediate/Build/Win64/UE4Editor/Inc/RooVR/CallHelper.generated.h.conflict'`
>` Info Error: UnrealHeaderTool failed for target 'RooVREditor' (platform: Win64, module info: C:\Users\Jamie\Dropbox\RooVR\Intermediate\Build\Win64\RooVREditor\Development\RooVREditor.uhtmanifest, exit code: OtherCompilationError (5)).`

**Comment by jrgalim** [comment]
Does Unreal.hx require compilation outside of the editor (UnrealBuildTool)?

**Comment by datee** [comment]
I have unreal.hx up and running with 4.16.3 and Haxe 3.4.2.
Just download the 4.16 branch, put it into "plugins/unrealhx" and change the .uproject file like it says above. Change the build.cs file under source to extend "HaxeModuleRules" instead of "ModuleRules". Open Visual studio and hit compile, and you should be good to go! Requires a UE c++ project.

**Comment by jrgalim** [comment]
Success, thank you!  Also, as a note, you can start with a blueprint project, and convert it to a hybrid blueprint/c++ project by just creating a new empty class in the editor.
