### ISSUE TITLE
Compile Error Using CreateDefaultSubobject()

### ISSUE THREAD

**Issue by jrgalim** [proletariatgames/unreal.hx#67]
Hello, I've been trying to get CreateDefaultSubobject to work after referencing it's usage in the Platformer port's ClimbMarker class, but keep getting an error.  Here it is in the ClimbMarker:
`var SceneComp = init.CreateDefaultSubobject(new TypeParam<USceneComponent>(), this, "SceneComp", false);`
...and then mine:
`FirstPersonCameraComponent = init.CreateDefaultSubobject(new TypeParam<UCameraComponent>(), this, "FirstPersonCamera", false);`
... and then the error:
`characters 121-126 : Bool should be unreal.UClass For function argument 'ReturnType'`

Does anyone have a clue what I'm doing wrong?  I'm using UE4.16, so it's possible that function definition has changed since 4.11.

-Jamie

**Comment by waneck** [comment]
Hi there! It seems you are using the ue4.16 branch, is that right?
We are currently changing some APIs to avoid the use of C++ templates when we can. That's part of an effort to make cppia depend less and less on a C++ recompilation.
In this case, the `CreateDefaultSuboject` function has changed to include the UClass to be generated:
https://github.com/proletariatgames/unreal.hx/blob/ue4.16/Haxe/Externs/Common/unreal/FObjectInitializer.hx#L9

Your code would then look like:
```haxe
FirstPersonCameraComponent = init.CreateDefaultSubobject(new TypeParam<UCameraComponent>(), this, "FirstPersonCamera", UCameraComponent.StaticClass());
```
Now optional arguments work, so you don't have to set all arguments (in the case of `false` for `bTransient`).

If you still would like to use type parameters, in some cases the old API is available with the `_Template` suffix, like https://github.com/proletariatgames/unreal.hx/blob/ue4.16/Haxe/Externs/Common/unreal/FObjectInitializer.hx#L13

This all should be documented once we actually make a release and merge ue4.16 with master

**Comment by waneck** [comment]
I'm closing this for now, but feel free to reopen if you feel there is a bug

**Comment by waneck** [comment]
Oh - also note that `new TypeParam<UCameraComponent>()` is optional in this case - as the type parameter can be inferred from the context

**Comment by jrgalim** [comment]
Ah, well that's awesome.  Thanks for the quick response!  Your solution worked perfectly.
