### ISSUE TITLE
Game Crashes When Calling Montage_Play()

### ISSUE THREAD

**Issue by jrgalim** [proletariatgames/unreal.hx#68]
So I've been porting UE4's First-Person Shooter template to unreal.hx, and I'm very close, there's just one area that's causing some frustration.  When my FP weapon fires, I'm trying to play the fire animation, and referencing the original C++, it looks like I should be using Montage_IsPlaying() like this:

>if (FireAnimation != null)
>{
>// Get the animation object for the arms mesh
>var AnimInstance:UAnimInstance = Mesh1P.GetAnimInstance();
>if (AnimInstance != null)
>{
>//trace("Anim Instance exists");
>trace("Montage playing: "+AnimInstance.Montage_IsPlaying(null) );
>//AnimInstance.Montage_Play(FireAnimation, 1.0);
>}
>}

However, when I run it in-game, UE4 crashes with this:

> C++ EH exception - code e06d7363 (first/second chance not available)
> 
> KERNELBASE
> VCRUNTIME140
> UE4Editor_RooVR_1506!hx::Throw() [c:\haxetoolkit\haxe\lib\hxcpp\3,4,64\src\hx\stdlibs.cpp:54]
> UE4Editor_RooVR_1506!__hxcpp_dbg_checkedThrow() [c:\haxetoolkit\haxe\lib\hxcpp\3,4,64\include\hx\debug.h:350]
> UE4Editor_RooVR_1506!hx::NullReference() [c:\haxetoolkit\haxe\lib\hxcpp\3,4,64\src\hx\debug.cpp:440]
> UE4Editor_RooVR_1506!hx::ObjectPtr<hx::EnumBase_obj>::operator->() [c:\haxetoolkit\haxe\lib\hxcpp\3,4,64\include\hx\object.h:377]
> UE4Editor_RooVR_1506!_hx_getEnumValueIndex() [c:\haxetoolkit\haxe\lib\hxcpp\3,4,64\include\enum.h:157]
> UE4Editor_RooVR_1506!unreal::UAnimInstance_obj::Montage_Play() [c:\users\jamie\dropbox\roovr\intermediate\haxe\roovr-win-development-editor\static\src\unreal\uaniminstance.cpp:892]
> UE4Editor_RooVR_1506!unreal::__s_Montage_Play() [c:\users\jamie\dropbox\roovr\intermediate\haxe\roovr-win-development-editor\static\src\unreal\uaniminstance.cpp:3325]
> UE4Editor_RooVR_1506!hx::CallHaxe::run<null>() [c:\haxetoolkit\haxe\lib\hxcpp\3,4,64\src\hx\cppia\cppia.cpp:1727]
> UE4Editor_RooVR_1506!hx::CallHaxe::runVoid() [c:\haxetoolkit\haxe\lib\hxcpp\3,4,64\src\hx\cppia\cppia.cpp:1744]
> UE4Editor_RooVR_1506!hx::IfExpr::runVoid() [c:\haxetoolkit\haxe\lib\hxcpp\3,4,64\src\hx\cppia\cppia.cpp:541]
> UE4Editor_RooVR_1506!hx::BlockExpr::runVoid() [c:\haxetoolkit\haxe\lib\hxcpp\3,4,64\src\hx\cppia\cppia.cpp:433]
> UE4Editor_RooVR_1506!hx::IfExpr::runVoid() [c:\haxetoolkit\haxe\lib\hxcpp\3,4,64\src\hx\cppia\cppia.cpp:541]
> UE4Editor_RooVR_1506!hx::BlockExpr::runVoid() [c:\haxetoolkit\haxe\lib\hxcpp\3,4,64\src\hx\cppia\cppia.cpp:433]
> UE4Editor_RooVR_1506!hx::ScriptCallable::runFunctionClosure() [c:\haxetoolkit\haxe\lib\hxcpp\3,4,64\src\hx\cppia\cppiafunction.cpp:485]
> UE4Editor_RooVR_1506!hx::CppiaClosure::doRun() [c:\haxetoolkit\haxe\lib\hxcpp\3,4,64\src\hx\cppia\cppiafunction.cpp:651]
> UE4Editor_RooVR_1506!hx::CppiaClosure::__run() [c:\haxetoolkit\haxe\lib\hxcpp\3,4,64\src\hx\cppia\cppiafunction.cpp:730]
> UE4Editor_RooVR_1506!cpp::Variant::operator()() [c:\haxetoolkit\haxe\lib\hxcpp\3,4,64\include\cpp\variant.h:309]
> UE4Editor_RooVR_1506!uhx::expose::Character_Expose::OnFire() [c:\users\jamie\dropbox\roovr\intermediate\haxe\roovr-win-development-editor\static\src\uhx\expose\character_expose.cpp:215]

Any guidance would be much appreciated.  Thanks!

**Comment by waneck** [comment]
By looking at the stack strace, it seems that there was a null reference. My first guess, if the problem is at this function, is that `Mesh1P` is null.

However, `Character_Expose.OnFire` should have caught that exception and traced an error message if you're playing in editor. That makes me think if the problem is not related to hot reloading somehow.

Could you delete everything in your game `Binaries` folder, and let Unreal rebuild it when you launch the editor again? Once this is done, let me know if the error still persists.
Also - is the function in any case defined with the `@:live` metadata?

**Comment by jrgalim** [comment]
Thank you for taking a look.  I cleared out the `Binaries `folder, but that didn't work, and there's no `@:live` metadata used.  The weird thing is that I can call any other `AnimInstance.Montage_*` function, just not `Montage_Play()`, so `Mesh1P `does exist, as does `AnimInstance` and `FireAnimation`.

**Comment by waneck** [comment]
Okay, I now see what's going on. It's expecting an optional `unreal.EMontagePlayReturnType` value, but it can't handle when that value is null. I'm going to have it fixed - but for now, you can set the next argument to `MontageLength`

**Comment by jrgalim** [comment]
That worked, thank you!  For reference: the exact line:
`AnimInstance.Montage_Play(FireAnimation, 1.0, EMontagePlayReturnType.MontageLength);`

**Comment by waneck** [comment]
I'm reopening this because the optional argument should be set automatically if you don't specify it - instead of crashing

**Comment by waneck** [comment]
BTW, Haxe should be able to infer that a `EMontagePlayReturnType` type is expected, so just setting it to `MontageLength` should work as well
