### ISSUE TITLE
[4.16] Editor crashing when adding new classes to "scripts"

### ISSUE THREAD

**Issue by datee** [proletariatgames/unreal.hx#69]
Tested on Windows 10, Haxe 3.4.2, Unreal 4.16.3, Unreal.hx 4.16 branch:

Adding new **@:uclass** classes to the scripts folder and compiling for cppia seems to produce a crash in UE if the editor is open. Doing a full build works as expected, and cppia compilation on already existing classes  built with a full build works fine.  

Stack trace:
>	UE4Editor-CoreUObject.dll!StaticAllocateObjectErrorTests(UClass * InClass, UObject * InOuter, FName InName, EObjectFlags InFlags) Line 2158	C++
 	UE4Editor-CoreUObject.dll!StaticAllocateObject(UClass * InClass, UObject * InOuter, FName InName, EObjectFlags InFlags, EInternalObjectFlags InternalSetFlags, bool bCanRecycleSubobjects, bool * bOutRecycledSubobject) Line 2211	C++
 	UE4Editor-CoreUObject.dll!StaticConstructObject_Internal(UClass * InClass, UObject * InOuter, FName InName, EObjectFlags InFlags, EInternalObjectFlags InternalSetFlags, UObject * InTemplate, bool bCopyTransientsFromClassDefaults, FObjectInstancingGraph * InInstanceGraph, bool bAssumeTemplateIsArchetype) Line 3166	C++
 	UE4Editor-HX416test.dll!uhx::glues::UObject_Glue_obj::NewObject(unsigned __int64 outer, unsigned __int64 uclass, unreal::VariantPtr name, int flags, unsigned __int64 objTemplate, bool bCopyTransientsFromClassDefaults) Line 50	C++
 	UE4Editor-HX416test.dll!unreal::UObject_obj::NewObject(Dynamic T_TP, hx::ObjectPtr<unreal::UObject_obj> outer, hx::ObjectPtr<unreal::UClass_obj> uclass, unreal::VariantPtr name, Dynamic flags, hx::ObjectPtr<unreal::UObject_obj> objTemplate, Dynamic bCopyTransientsFromClassDefaults) Line 824	C++
 	UE4Editor-HX416test.dll!uhx::runtime::UReflectionGenerator_obj::createClass(hx::ObjectPtr<unreal::UObject_obj> outer, String uclassName, hx::ObjectPtr<unreal::UClass_obj> parent, bool parentHxGenerated, String hxPath) Line 1993	C++
 	UE4Editor-HX416test.dll!uhx::runtime::UReflectionGenerator_obj::getUpdatedClass(hx::ObjectPtr<uhx::runtime::DynamicRegistry_obj> reg) Line 692	C++
 	UE4Editor-HX416test.dll!uhx::runtime::UReflectionGenerator_obj::cppiaHotReload() Line 456	C++
 	UE4Editor-HX416test.dll!`UnrealInit_obj::editorSetup'::`2'::_hx_Closure_1::_hx_run() Line 408	C++
 	UE4Editor-HX416test.dll!`UnrealInit_obj::editorSetup'::`2'::_hx_Closure_1::__run() Line 529	C++
 	UE4Editor-HX416test.dll!Dynamic::operator()() Line 300	C++
 	UE4Editor-HX416test.dll!`UnrealInit_obj::editorSetup'::`2'::_hx_Closure_5::_hx_run(float deltaTime) Line 740	C++
 	UE4Editor-HX416test.dll!`UnrealInit_obj::editorSetup'::`2'::_hx_Closure_5::__run(const Dynamic & inArg0) Line 742	C++
 	UE4Editor-HX416test.dll!Dynamic::operator()(const Dynamic & inArg0) Line 301	C++
 	UE4Editor-HX416test.dll!uhx::expose::HxcppRuntime::callFunction1(unsigned __int64 ptr, unsigned __int64 arg0) Line 451	C++
 	UE4Editor-HX416test.dll!TBaseFunctorDelegateInstance<bool __cdecl(float),uhx::LambdaBinder<bool,float> >::Execute(float <Params_0>) Line 1132	C++
 	UE4Editor-Core.dll!FTicker::Tick(float DeltaTime) Line 82	C++
 	UE4Editor.exe!FEngineLoop::Tick() Line 3262	C++
 	UE4Editor.exe!GuardedMain(const wchar_t * CmdLine, HINSTANCE__ * hInInstance, HINSTANCE__ * hPrevInstance, int nCmdShow) Line 166	C++
 	UE4Editor.exe!WinMain(HINSTANCE__ * hInInstance, HINSTANCE__ * hPrevInstance, char * __formal, int nCmdShow) Line 199	C++

**Comment by waneck** [comment]
Okay, I've made an attempted fix at this. Let me know if this works

**Comment by datee** [comment]
Thanks! It seems this solves the issue! The editor does not crash now with the fix in place. New classes only compiled with cppia does not appear within the editor until a proper build is done but i guess this is expected behaviour?

**Comment by waneck** [comment]
Hmm that shouldn't be the expected behaviour

**Comment by waneck** [comment]
I'll check that

**Comment by datee** [comment]
Been trying out this for a while and it seems to work just totally fine. I'm closing this for now!
