### ISSUE TITLE
Ref being ignored when used in extern definition

### ISSUE THREAD

**Issue by datee** [proletariatgames/unreal.hx#72]
When setting up an extern for the following c++ function, the "Ref" operator is ignored and extern failes to compile:

C++
`bool GetRaw( const TArray < uint8 > *& OutRawData )
`

Haxe Extern:
`public function GetRaw(InFormat:Const<ERGBFormat>,InBitDepth:Int32,OutRaw:Ref<PPtr<Const<TArray<UInt8>>>>):Bool;`

Error :
```
[..../Generated/Private/uhx/glues/IImageWrapper_Glue.cpp(38): error C2664: 'bool IImageWrapper::GetRaw(const ERGBFormat::Type,int32,const TArray<uint8,FDefaultAllocator> *&)': cannot convert argument 3 from 'TArray<uint8,FDefaultAllocator> *' to 'const TArray<uint8,FDefaultAllocator> *&'
..../Intermediate/Haxe/HX416test-Win-Development-Editor/Generated/Private/uhx/glues/IImageWrapper_Glue.cpp(38): note: Conversion loses qualifiers
]
```

**Comment by waneck** [comment]
This should be fixed now. Note that the const position is important for this to work:
```public function GetRaw(inFormat:ERGBFormat, bitDepth:Int, outRawData:Ref<PPtr<Const<TArray<UInt8>>>>):Bool;```
