### ISSUE TITLE
Global Variables?

### ISSUE THREAD

**Issue by jrgalim** [proletariatgames/unreal.hx#75]
It appears that there is a variable in the UE4 c++, `GEngine`, which is an instance of `UEngine`, that exists at a global level.  Is it possible to create externs for global variables?  How would I achieve this in Haxe?  I know that "untyped" works for the javascript target, but I'd imagine that would be ill-advised for c++.  Thoughts?

**Comment by waneck** [comment]
Hi there! Sorry to take this long to answer. You can use `@:global` to extern global variables and externs. There are some examples on our own code base of this, like GEngine itself - https://github.com/proletariatgames/unreal.hx/blob/ee53c3330c03eef81cf95c84165e4ecc70eed26d/Haxe/Externs/Common/unreal/UEngine_Extra.hx#L30
