### ISSUE TITLE
Can't generate VS Project Files , Please help

### ISSUE THREAD

**Issue by Moonstrous** [proletariatgames/unreal.hx#78]
Here are the errors i get 😞 
`Running E:/UE4/UE_4.18/Engine/Binaries/DotNET/UnrealBuildTool.exe  -projectfiles -project="E:/Beast v2.07/uhx/uhx.uproject" -game -rocket -progress
Discovering modules, targets and source code for project...
While compiling E:\Beast v2.07\uhx\Intermediate\Build\BuildRules\uhxModuleRules.dll:
ERROR: e:\Beast v2.07\uhx\Plugins\unreal.hx\Source\HaxeInit\BuildApi.Build.cs(239,9) : error CS1502: The best overloaded method match for 'UnrealBuildTool.BuildVersion.TryRead(Tools.DotNETCommon.FileReference, out UnrealBuildTool.BuildVersion)' has some invalid arguments
ERROR: e:\Beast v2.07\uhx\Plugins\unreal.hx\Source\HaxeInit\BuildApi.Build.cs(239,30) : error CS1503: Argument 1: cannot convert from 'string' to 'Tools.DotNETCommon.FileReference'
ERROR: e:\Beast v2.07\uhx\Plugins\unreal.hx\Source\HaxeInit\BuildApi.Build.cs(362,10) : error CS0718: 'UnrealBuildTool.UProjectInfo': static types cannot be used as type arguments
ERROR: e:\Beast v2.07\uhx\Plugins\unreal.hx\Source\HaxeInit\BuildApi.Build.cs(362,45) : error CS0117: 'UnrealBuildTool.UProjectInfo' does not contain a definition for 'FilterGameProjects'
ERROR: e:\Beast v2.07\uhx\Plugins\unreal.hx\Source\HaxeInit\BuildApi.Build.cs(365,28) : error CS0117: 'UnrealBuildTool.UProjectInfo' does not contain a definition for 'FilterGameProjects'
ERROR: e:\Beast v2.07\uhx\Plugins\unreal.hx\Source\HaxeInit\BuildApi.Build.cs(371,31) : error CS1061: 'UnrealBuildTool.UProjectInfo' does not contain a definition for 'Folder' and no extension method 'Folder' accepting a first argument of type 'UnrealBuildTool.UProjectInfo' could be found (are you missing a using directive or an assembly reference?)
ERROR: UnrealBuildTool Exception: Unable to compile source files.`

**Comment by waneck** [comment]
Hi there! Thanks for the bug report. I noticed that you are using unreal
4.18 with this project. Unfortunately it's still not supported - the latest
supported version is 4.17 . We have plans to update the version soon

**Comment by Moonstrous** [comment]
Thanks for the quick reply :) , When will it be updated ? , and a second question if you may allow , Can you extend the editor (and create extensions / plugins ) with Unreal.hx , like in UEPython , and Unreal.JS ... etc ?
And just a tip , The more documentation you have , the more people will contribute and use what you create , at least that is what the people say in Game Dev League and Unreal Slackers ... etc I plan to write docs for Unreal.hx !
Thanks again 😄

**Comment by waneck** [comment]
We've just updated to 4.19!
About extending the editor, you can. You can conditionally compile some code only when the editor is being built by leveraging Haxe's conditional compilation - e.g. `#if WITH_EDITOR`

**Comment by waneck** [comment]
And documentation update will be more than welcome :) Let me know if you need anything!

**Comment by waneck** [comment]
Closing for lack of response
