### ISSUE TITLE
Compile Error in MethodPointer.hx

### ISSUE THREAD

**Issue by jrgalim** [proletariatgames/unreal.hx#84]
I just did a fresh install into a 4.19 project with the latest branch, and I'm getting a compile error relating to MethodPointer:

```
\Plugins\UnrealHx/Haxe/Static/unreal/MethodPointer.hx:59: characters 21-70 : 
unreal.MethodPointer<Unknown<0>, Unknown<1>> should be Float -> Void
For function argument 'func'
```

Has anyone else received this error?

EDIT:
For additional information, I am porting some code from a 4.16 project, where I am using MethodPointer to bind functions to input actions.  I suppose it's possible this process has changed since that version.

EDIT 2:
Turns out BindAction/BindAxis don't need MethodPointers anymore, so I can proceed regardless of this error.

**Comment by waneck** [comment]
Hey! Sorry it took me so long to answer you!

Seems like you solved it!
